### PR TITLE
Allow user to log detailed rule report

### PR DESCRIPTION
**Pull request by shivan1b**
Add a `--report <filename>` option so that the end user is able to log a
report about the rules enabled, disabled, modified and dropped.
Usage
```
└─ $ ▶ ./bin/suricata-update --report /tmp/rules.log
```

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/2256

### CODE REVIEW

**Comment by victorjulien** [comment]
Can you add a sample report to this or the next PR?

**Comment by shivan1b** [comment]
@victorjulien Sure. Waiting for Jason's comments too, shall do it in the v2.

**Comment by jasonish** [comment]
When print the rules, we don't need the full rule, just the msg, sid and rev is good. The rule object has a .breif() method that prints this short version.

We're also missing the added/removed/modified that I get in this log line:
```
21/12/2018 -- 09:34:59 - <Info> -- Writing rules to ./data/rules/suricata.rules: total: 26849; enabled: 19443; added: 7; removed 0; modified: 0
```

**Comment by shivan1b** [comment]
Please have a look at #86

**Pull request closed without merging**
