### PR TITLE
Move dataset and filemd5 files alongwith rules

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3528
https://redmine.openinfosecfoundation.org/issues/2688

### CODE REVIEW

**Comment by inashivb** [comment]
@jasonish seems like rebasing this PR over #212  would take care of duplicate names for the files as well? Please let me know if this is an incorrect interpretation.

**Comment by jasonish** [comment]
Ok, the basics now work, but needs to expanded:

- The filemd5 handling of data files should be made generic over filemd5, filesha1 and filesha256.
- Handle datafiles in a subdirectory, for example if the rule has `filemd5:datafiles/md5.list`, and the rule archive contains `rules/datafiles/md5.list` it should be found

Issues to think about:
- If 2 sources include `rules/datafiles/md5.list` one will be lost when the rules are loaded into the dict. PR #212 will solve that problem. But this feature will need to handle the conflict when writing out the files to disk.
- Removing files from the rule directory when they are no longer referenced by any rules.

**Comment by jasonish** [comment]
My latest test rule file:
[rules.tar.gz](https://github.com/OISF/suricata-update/files/4409833/rules.tar.gz)

**Comment by inashivb** [comment]
Thanks, Jason. Please check the new PR #222

**Pull request closed without merging**
