### PR TITLE
Move dataset and filemd5 files alongwith rules

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/3528
https://redmine.openinfosecfoundation.org/issues/2688

Notes from previous PR by Jason:

> Issues to think about:
>    - If 2 sources include rules/datafiles/md5.list one will be lost when the rules are loaded into the dict. PR #212 will solve that problem. But this feature will need to handle the conflict when writing out the files to disk.
>  -   Removing files from the rule directory when they are no longer referenced by any rules

### CODE REVIEW

**Comment by jasonish** [comment]
Given my rule archive that looks like (attached)
```
rules/filemd5.list
rules/datafiles
rules/datafiles/filesha256.list
rules/datafiles/filesha1.list
rules/test.rules
```
the output of Suricata-Update looks like:
```
data/rules/filesha256.list
data/rules/filesha1.list
data/rules/suricata.rules
data/rules/filemd5.list
```
The `list` files are in the same directory as the rule file, but the rules are still looking for the files in a `datafiles` directory. Suricata will fail to load the rules with an error like:
```
[1407815] 8/4/2020 -- 11:16:20 - (detect-file-hash-common.c:249) <Error> (DetectFileHashParse) -- [ERRCODE: SC_ERR_OPENING_RULE_FILE(41)] - opening hash file ../../suricata-update/datasets/data/datafiles/filesha1.list: No such file or directory
```

So the output directory needs to respect the input directory layout for these datafiles.

**Comment by inashivb** [comment]
> Given my rule archive that looks like (attached)
> 
> ```
> rules/filemd5.list
> rules/datafiles
> rules/datafiles/filesha256.list
> rules/datafiles/filesha1.list
> rules/test.rules
> ```
> 
> the output of Suricata-Update looks like:
> 
> ```
> data/rules/filesha256.list
> data/rules/filesha1.list
> data/rules/suricata.rules
> data/rules/filemd5.list
> ```
> 
> The `list` files are in the same directory as the rule file, but the rules are still looking for the files in a `datafiles` directory. Suricata will fail to load the rules with an error like:
> 
> ```
> [1407815] 8/4/2020 -- 11:16:20 - (detect-file-hash-common.c:249) <Error> (DetectFileHashParse) -- [ERRCODE: SC_ERR_OPENING_RULE_FILE(41)] - opening hash file ../../suricata-update/datasets/data/datafiles/filesha1.list: No such file or directory
> ```
> 
> So the output directory needs to respect the input directory layout for these datafiles.

I see. Please let me know if I understood correctly, you are suggesting to update the rules with the absolute path that we are moving the file to. Is that correct?

**Comment by jasonish** [comment]
> I see. Please let me know if I understood correctly, you are suggesting to update the rules with the absolute path that we are moving the file to. Is that correct?

No, I'd just make sure the list files get put into a directory where the rule expects to find them. Shouldn't need to update that rule itself.

We need to avoid absolute paths as someone may run Suricata-Update, package up the output directory and push it out to their sensors where the paths may be different.

So the output directory in this case should look like:
```
data/rules/datafiles/filesha256.list
data/rules/filesha1.list
data/rules/suricata.rules
data/rules/datafiles/filemd5.list
```

We may have to get into rule rewriting the rules to avoid filename clashes.. For example, if 2 rules from different sources include a data file of the same name, but are different. Then we'll have to rename the datafiles and update the rules. But will still keep a relative path.

**Comment by inashivb** [comment]
> > I see. Please let me know if I understood correctly, you are suggesting to update the rules with the absolute path that we are moving the file to. Is that correct?
> 
> No, I'd just make sure the list files get put into a directory where the rule expects to find them. Shouldn't need to update that rule itself.
> 
> We need to avoid absolute paths as someone may run Suricata-Update, package up the output directory and push it out to their sensors where the paths may be different.
> 
> So the output directory in this case should look like:
> 
> ```
> data/rules/datafiles/filesha256.list
> data/rules/filesha1.list
> data/rules/suricata.rules
> data/rules/datafiles/filemd5.list
> ```
> 
> We may have to get into rule rewriting the rules to avoid filename clashes.. For example, if 2 rules from different sources include a data file of the same name, but are different. Then we'll have to rename the datafiles and update the rules. But will still keep a relative path.

Thanks, Jason!
I see on Suricata test that the dir expected is
```
3/5/2020 -- 02:06:42 - <Error> -- [ERRCODE: SC_ERR_OPENING_RULE_FILE(41)] - opening hash file /var/lib/suricata/datafiles/filesha1.list: No such file or directory
```
It seems to be skipping `/rules/`. state_dir + whatever was in the rule seems to be the path where Suricata looks into. Is this the right path or am I doing something wrong?

**Comment by jasonish** [comment]
> It seems to be skipping `/rules/`. state_dir + whatever was in the rule seems to be the path where Suricata looks into. Is this the right path or am I doing something wrong?

Looks like an issue with Suricata. When using -S, and the rule file falls outside of default-rule-path, it can't find the datafiles.  We can probably fix this with some --set command line options.

But first, I'm stuck with these errors when I run suricata-update against my test rule archive:
```
28/5/2020 -- 11:38:01 - <Error> -- filemd5 file fileextraction-chksum.list was not found
28/5/2020 -- 11:38:01 - <Error> -- filesha1 file fileextraction-chksum.list was not found
28/5/2020 -- 11:38:01 - <Error> -- filesha256 file fileextraction-chksum.list was not found
```
My command line is:
```
./bin/suricata-update -D ./data --url file:///home/jason/oisf/code/suricata-update/rules.tar.gz
```
and rule
[rules.tar.gz](https://github.com/OISF/suricata-update/files/4697326/rules.tar.gz)
s.tar.gz is attached.

**Comment by inashivb** [comment]
> > It seems to be skipping `/rules/`. state_dir + whatever was in the rule seems to be the path where Suricata looks into. Is this the right path or am I doing something wrong?
> 
> Looks like an issue with Suricata. When using -S, and the rule file falls outside of default-rule-path, it can't find the datafiles. We can probably fix this with some --set command line options.
> 
> But first, I'm stuck with these errors when I run suricata-update against my test rule archive:
> 
> ```
> 28/5/2020 -- 11:38:01 - <Error> -- filemd5 file fileextraction-chksum.list was not found
> 28/5/2020 -- 11:38:01 - <Error> -- filesha1 file fileextraction-chksum.list was not found
> 28/5/2020 -- 11:38:01 - <Error> -- filesha256 file fileextraction-chksum.list was not found
> ```
> 
> My command line is:
> 
> ```
> ./bin/suricata-update -D ./data --url file:///home/jason/oisf/code/suricata-update/rules.tar.gz
> ```
> 
> and rule
> [rules.tar.gz](https://github.com/OISF/suricata-update/files/4697326/rules.tar.gz)
> s.tar.gz is attached.

Thanks, Jason. Please see the updated PR #234 
Please note that it only covers the full functionality for filemd5. datasets have not been tested yet. The rule archive you provided seems to be passing with that but it still has the issue of `/rules/` missing in the paths.

**Pull request closed without merging**
