### PR TITLE
Add warning to update sources if no index found

### PR DESCRIPTION
**Pull request by TharushiJay**
- [x] I have read the contributing guide lines at
  https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation
  contribution agreement at
  https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the
  changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3249

Describe changes:
- Don't automatically update the sources on list-sources if it does not exist. Instead just use the bundled version.

### CODE REVIEW

**Comment by inashivb** [comment]
Thanks for your first contribution to the project! :)
I'll wait for Jason to respond but since its very close to completion, you can now claim another ticket.

Good job!

**Comment by TharushiJay** [comment]
Great! Thank you Shivani. I really enjoyed working on this project.

**Review by jasonish — CHANGES_REQUESTED** [review]
Thanks. Code looks good, tests OK.

As this does change the behaviour I'd like to see more info in the commit message.  The first line of the message is fine. But the body of the commit message should contain a little more detail along the lines of:

Don't automatically update the sources on list-sources if it does not exist. Instead just use the bundled version.

**Comment by TharushiJay** [comment]
> Thanks. Code looks good, tests OK.
> 
> As this does change the behaviour I'd like to see more info in the commit message. The first line of the message is fine. But the body of the commit message should contain a little more detail along the lines of:
> 
> Don't automatically update the sources on list-sources if it does not exist. Instead just use the bundled version.


@jasonish I updated the body of the commit message (under 'Describe changes') to reflect the details you mentioned. Is there anything else I could change to get this PR approved?

**Comment by jasonish** [comment]
> > Thanks. Code looks good, tests OK.
> > As this does change the behaviour I'd like to see more info in the commit message. The first line of the message is fine. But the body of the commit message should contain a little more detail along the lines of:
> > Don't automatically update the sources on list-sources if it does not exist. Instead just use the bundled version.
> 
> @jasonish I updated the body of the commit message (under 'Describe changes') to reflect the details you mentioned. Is there anything else I could change to get this PR approved?

@TharushiJay You did update the pull request message.  But I'd like the commit message to be updated as well. This can be done with the "reword" feature of a git rebase. If you are not familar with that feature, I'm happy to list out the commands here.

**Comment by TharushiJay** [comment]
> @TharushiJay You did update the pull request message. But I'd like the commit message to be updated as well. This can be done with the "reword" feature of a git rebase. If you are not familar with that feature, I'm happy to list out the commands here.

Sorry, my mistake! I wasn't aware of changing the 'body of the commit message'. Thank you @jasonish. 
Please let me know if this works.

**Review by jasonish — CHANGES_REQUESTED** [review]
Commit change tweaks.

**Comment by TharushiJay** [comment]
> Close, again the code is fine, but the formatting of the commit message needs to be fixed. In general the first line should be something like:
> 
> ```
> Add warning to update sources if no index found
> ```
> 
> Usually this should be limited to 72 characters.
> 
> Then after that first line, leave one blank link then the body:
> 
> ```
> Don't automatically update the sources on list-sources 
> if it does not exist. Instead just use the bundled version.
> ```
> 
> The body should be word-wrapped at 72 cols as well.
> 
> This all helps to provide a better reading experience in the "git log" output.
> 
> Thanks.

@jasonish Thanks for the helpful advice. I've made the necessary changes. Please let me know if this works.

**Comment by jasonish** [comment]
Merged in master via https://github.com/OISF/suricata-update/pull/292, Thanks!

**Pull request closed without merging**
