### PR TITLE
Move dataset and filemd5 files alongwith rules

### PR DESCRIPTION
**Pull request by inashivb**
Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket:
https://redmine.openinfosecfoundation.org/issues/2688
https://redmine.openinfosecfoundation.org/issues/3528

### CODE REVIEW

**Comment by jasonish** [comment]
Merged. Thanks!

**Comment by Kolano** [comment]
I'm still not seeing files from the OTX rule set copied in v1.2.1.

Rules like this...
`alert http any any -> $HOME_NET any (msg:"OTX - FILE MD5 from pulse b'ChaChi: a New GoLang RAT'";  `filemd5:60d344aae66268d9b2a55c3a.txt; reference: url, otx.alienvault.com/pulse/60d344aae66268d9b2a55c3a; sid:411751; rev:1;)
...with the 60d344aae66268d9b2a55c3a.txt file stored in the same /etc/suricata/rules directory as the rules, still result in errors...
`23/6/2021 -- 21:08:34 - <Error> -- filemd5 file 60d344aae66268d9b2a55c3a.txt was not found`
...and no file seems to be copied.

**Comment by inashivb** [comment]
> I'm still not seeing files from the OTX rule set copied in v1.2.1.
> 
> Rules like this...
> `alert http any any -> $HOME_NET any (msg:"OTX - FILE MD5 from pulse b'ChaChi: a New GoLang RAT'"; filemd5:60d344aae66268d9b2a55c3a.txt; reference: url, otx.alienvault.com/pulse/60d344aae66268d9b2a55c3a; sid:411751; rev:1;)`
> ...with the 60d344aae66268d9b2a55c3a.txt file stored in the same /etc/suricata/rules directory as the rules, still result in errors...
> `23/6/2021 -- 21:08:34 - <Error> -- filemd5 file 60d344aae66268d9b2a55c3a.txt was not found`
> ...and no file seems to be copied.

Thanks, @Kolano . We shall check again and give an update about this.

**Comment by jasonish** [comment]
Also @Kolano, Suricata-Update does not use the `/etc/suricata/rules` directory, so can you include how you are running `Suricata-Update` (chaning default paths by chance?) and how you are pointing Suricata at these rules?

We also don't have access to the OTX, can you tell us how they are organized? Maybe a listing of the .tar.gz (or zip, etc) would be enough. Thanks!

**Pull request closed without merging**
