### PR TITLE
Opt 3205/v2

### PR DESCRIPTION
**Pull request by Riju19**
Make sure these boxes are signed before submitting your Pull Request
-- thank you.

- [x] I have read the contributing guide lines at
  https://redmine.openinfosecfoundation.org/projects/suricata/wiki/Contributing
- [x] I have signed the Open Information Security Foundation
  contribution agreement at
  https://suricata-ids.org/about/contribution-agreement/
- [ ] I have updated the user guide (in doc/userguide/) to reflect the
  changes made (if applicable)

Link to [redmine](https://redmine.openinfosecfoundation.org/projects/suricata/issues) ticket: https://redmine.openinfosecfoundation.org/issues/3205

Describe changes:
This pull request contains logging enhancements for flowbit requirements.

### CODE REVIEW

**Comment by jasonish** [comment]
Can you please confirm if you have signed the contributor agreement at https://suricata-ids.org/about/contribution-agreement/ ?  I can't find your submission. Thanks!

**Review by jasonish — CHANGES_REQUESTED** [review]
Can you please squash these 2 commits together so one is fixing the previous commit? Maybe add something to log the message it add the "pass" to the output.  Thanks.

**Comment by jasonish** [comment]
Code looks good. I'd like to see the commit fixed up a bit.
- Can you please use your full name in the commit message so it matches the full name in your contribution agreement (`git config user.name ...`).
- The first line of the commit message is fine. However, can you wrap the body of the commit message at 72 characters?

And for the next PR, please follow our guideline of submitting a new version of the pull request. Thanks!

**Review by jasonish — CHANGES_REQUESTED** [review]
Changes requested. Please see previous comment.

**Comment by Riju19** [comment]
> Code looks good. I'd like to see the commit fixed up a bit.
> 
>     * Can you please use your full name in the commit message so it matches the full name in your contribution agreement (`git config user.name ...`).
> 
>     * The first line of the commit message is fine. However, can you wrap the body of the commit message at 72 characters?
> 
> 
> And for the next PR, please follow our guideline of submitting a new version of the pull request. Thanks!

Got it! Here's the next version of this : https://github.com/OISF/suricata-update/pull/265
Should we close this one and the previous one?

**Comment by jasonish** [comment]
> Should we close this one and the previous one?

Yes. When a new version is created you can close the current one with a link to the new one. Its also useful to link the the "Previous PR" in the new version as well.

**Comment by jasonish** [comment]
Continued at https://github.com/OISF/suricata-update/pull/265.

**Pull request closed without merging**
